{
  "hash": "8ae433378eb00debaa7a6bc7674ba574",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hypothesis Testing and Confidence Intervals\" # Also check out line 43\ndate: '2025-11-24'\ndocumentclass: scrartcl\nexecute: \n  freeze: auto\nformat: \n  html: # Settings set in _metadata.yml\n    toc: true\n  pdf:\n    include-in-header: \n      text: |\n        \\usepackage{lmodern} \n        \\usepackage{graphicx}\n        \\usepackage{hyperref}\n        \\usepackage{url}                \n        \\usepackage{xcolor}\n        \\usepackage{booktabs}\n        \\usepackage{listings}\n        \\lstloadlanguages{R}\n        \n        \\definecolor{eufblue}{RGB}{0,57,91}\n        \\definecolor{eufgrey}{RGB}{111,111,111}\n        \\definecolor{euflightblue}{RGB}{105,170,205}\n        \n        \\hypersetup{\n        pdfauthor={Claudius Graebner-Radkowitsch}\n        colorlinks=true,\n        linkcolor=euflightblue,\n        urlcolor=euflightblue\n        }\n        \\usepackage[includehead,includefoot,top=2cm, bottom=1.5cm]{geometry}\n        \\usepackage[headsepline, footsepline]{scrlayer-scrpage}\n        \\pagestyle{scrheadings}\n        \\clearpairofpagestyles\n        \\ihead{Tutorial: Visualization}\n        %\\chead{Kopfzeile Mitte}\n        \\ohead{\\pagemark} %\n        \\ifoot{}\n        \\cfoot{\\href{https://researchmethodology-fall26.netlify.app/}{\\normalfont\\color{eufblue}{Data Science Using R - Fall Semester 2026}}} % Fußzeile Mitte\n        \\ofoot{} \n        \\setkomafont{disposition}{\\color{eufblue}\\bfseries}\n---\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Packages used for R examples\"}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(ggpubr)\nlibrary(latex2exp)\nlibrary(moderndive)\nlibrary(DataScienceExercises)\nlibrary(kableExtra)\n```\n:::\n\n\n## Introduction: From Sampling to Inference\n\nIn Lecture 11, you learned about the fundamental concepts of sampling: how we draw conclusions about unknown populations by studying samples, and how the Central Limit Theorem provides the theoretical foundation for making these inferences. Among the key take aways from this lecture were the following:\n\n- **Populations** have parameters ($\\mu$, $\\sigma$) that are typically unknown\n- **Samples** provide statistics ($\\bar{x}$, $s$) that we can use to estimate these parameters  \n- **Sampling distributions** describe how sample statistics vary across different samples\n- **Standard errors** quantify the precision of our estimates\n\nNow we face two crucial questions that arise in almost every business and research context:\n\n1. **Testing claims:** \"Someone claims the average customer satisfaction is 8.0/10. Based on my sample of 100 customers with mean 7.5, should I believe this claim?\"\n\n2. **Quantifying uncertainty:** \"My sample of 500 SMEs in Schleswig Holstein shows average monthly revenue of EUR 50,000. What's the plausible range for the true population mean of all SMEs in Schleswig Holstein?\"\n\nThese questions represent two main approaches to statistical inference:\n\n- **Hypothesis testing:** Evaluating specific claims using sample data\n- **Confidence intervals:** Constructing ranges of plausible values for parameters\n\nBoth build directly on the sampling concepts you've learned, and both are essential for interpreting the regression models you'll study in later lectures.\n\n::: {.callout-note collapse=\"true\"}\n## When to read this tutorial\n\nI suggest you read this tutorial after having heard the lecture on sampling. The concepts in this tutorial — particularly hypothesis testing — make much more sense once you've seen how sampling works through Monte Carlo simulations and understand sampling distributions intuitively. But if you feel more or less comfortable in these areas you can also read it directly after the recap text on probability theory as I also included a very concise recap of this session below.\n:::\n\n### Learning Objectives\n\nBy the end of this tutorial, you will be able to:\n\n- Construct and interpret hypothesis tests for business decisions\n- Calculate and explain confidence intervals for population parameters  \n- Distinguish between statistical and practical significance\n- Avoid common misinterpretations of $p$-values and confidence intervals\n- Connect these concepts to the regression output you'll encounter later on\n- Recognize when hypothesis testing is (and isn't) the appropriate tool\n\n---\n\n## 1. Quick Recap: Essential Concepts from Sampling\n\nBefore diving into inference, let's briefly review the key concepts from our sampling section that form the foundation for everything in this session.\n\n### The Sample-Population Relationship\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**Key points to remember:**\n\n**Population:**\n\n- The complete group we want to learn about\n- Has fixed parameters ($\\mu$, $\\sigma$, etc.) that are typically unknown\n- Example: All customers of a company, all products in a market\n\n**Sample:**\n\n- A subset of the population we actually observe\n- Provides statistics ($\\bar{x}$, $s$) that we can use to estimate population parameters\n- Random sampling common to improve representativeness, but also means each sample usually shows different sample statistics\n\n**The inference challenge:**\n\n- We observe: Sample statistics ($\\bar{x}$ = 64.2)\n- We want to know: Population parameter ($\\mu$ = ?)\n- The potential gap between these creates uncertainty\n\n### Sampling Distributions\n\nThis was one of the crucial statement from the sampling lecture: \nif we could draw many samples from the same population, each sample would give us a slightly different estimate due to sampling variation. While in reality we usually draw only one sample, the *sampling distribution* provides us with important information about how to interpret the results obtained from this single sample.\n\n**The sampling distribution** describes how these sample statistics (like $\\bar{x}$) are distributed across many different samples. This is relevant even (or *especially*) when we draw only sample as it helps us to quantify the uncertainty associated with using the statistics obtained from this sample.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nIn the cases where the Central Limit Theorem (CLT) holds, the sampling distribution has the following properties:\n\n1. **Center:** The sampling distribution centers on the true population parameter ($\\mu$)\n2. **Spread:** The standard deviation of this distribution is the **standard error** (SE):\n   $$SE = \\frac{\\sigma}{\\sqrt{n}}$$\n3. **Shape:** For large enough samples, it's approximately normal regardless of the underlying population distribution\n\n**Why this matters:**\n\n- The standard error tells us how much sampling variation to expect\n- Smaller SE (from larger $n$) means more precise estimates (so we can trust the sample statistics more)\n- The normal shape lets us calculate probabilities\n\n### Point Estimates and Their Uncertainty\n\n**Point estimate:** A single number calculated from sample data to estimate a population parameter\n\n- $\\bar{x}$ estimates $\\mu$ (population mean)\n- $s$ estimates $\\sigma$ (population standard deviation)  \n- $\\hat{p}$ estimates $p$ (population proportion)\n\n::: {.callout-warning collapse=\"true\"}\n## Reminder: be careful when choosing your estimator\n\nAn estimator is a procedure for producing an estimate. The most straightforward was to produce an estimate for a population parameter (say, $\\mu$) is to choose its sample equivalent (here: $\\bar{x}$).\n\nBut remember the cautionary tales at the end of the lecture: it is not always a good idea to use the sample equivalents directly, as, for instance, in the case of the sample variance of the sample maximum.\n:::\n\n**The fundamental problem:** Point estimates alone don't convey information about uncertainty!\n\nIf I tell you \"average customer satisfaction is 7.5/10 based on my sample,\" you should ask:\n\n- How large was the sample?\n- How variable were the responses?\n- What's the plausible range for the true population mean?\n\nThis is where **hypothesis testing** and **confidence intervals** come in. They both use the sampling distribution to quantify uncertainty in principled ways.\n\n---\n\n## 2. Confidence Intervals: Quantifying Uncertainty\n\n### 2.1 The Concept\n\nImagine you're a marketing manager who surveyed 100 customers about monthly spending. Your sample shows:\n\n- Sample mean: $\\bar{x}$ = 250 EUR\n- Sample standard deviation: $s = 50$ EUR\n- Sample size: $n=100$\n\n**Question:** What's the true average spending for all customers ($\\mu$)?\n\n**Naive answer:** \"250 EUR\"\n\n- Just reports the point estimate, no information about uncertainty involved in the sample process\n\n**Better answer:** \"Somewhere between 240 EUR and 260 EUR\"\n\n- Reports a range; from the size of the range we can get information about the sampling uncertainty\n\n**Best answer:** \"Based on a method that works 95% of the time, I can say that the true average lies in the interval between 240.2 and 259.8 EUR.\"\n\n- This range is called a **confidence interval (CI)**, and it's one of the most important tools in statistics for communicating uncertainty.\n\n::: {.callout-important}\n## Speaking Correctly About Confidence Intervals\n\n**❌ INCORRECT formulations:**\n\n- \"There's a 95% probability that $\\mu$ is between 240 EUR and 260 EUR\"\n- \"We can be 95% certain that $\\mu$ is between 240 EUR and 260 EUR\"\n\n**Why these are wrong:** Once you've calculated a specific interval from your data, the true parameter $\\mu$ either is or isn't in that interval (probability = 1 or 0). The parameter is fixed, not random; the *interval* is what's random (it varies from sample to sample). These phrasings incorrectly suggest we're making probability statements about the parameter itself.\n\n**✅ CORRECT formulations:**\n\n- \"The interval [240 EUR, 260 EUR] was constructed using a procedure that captures the true parameter in 95% of samples\"\n- \"If we repeated this sampling process many times, approximately 95% of the resulting intervals would contain $\\mu$\"\n- \"This interval was calculated using a method with a 95% success rate\"\n\n**Acceptable shorthand (with important caveats):**\n\n- \"We are 95% confident the true mean is between 240 EUR and 260 EUR\"\n\nThis phrasing is widely used and generally accepted in practice, but it's imprecise. The word \"confident\" here should be understood as shorthand for \"confident in the procedure that generated this interval,\" not as subjective certainty about this particular interval. \n\n**The subtle but crucial distinction:** This shorthand is acceptable because \"confident\" (unlike \"probability\" or \"certain\") can refer to trust in a method rather than a claim about the parameter. However, it's easily misunderstood, so use it carefully.\n\n**Best practice:** When precision matters (academic writing, technical reports), use the explicit formulation about the procedure. In business contexts, the shorthand is acceptable if your audience understands it refers to the method's reliability.\n:::\n\n\n\n### 2.2 What is a Confidence Interval?\n\nA confidence interval is a range of values that is likely to contain the true population parameter, constructed using sample data and a specified confidence level.\n\n**General form for a mean:**\n\n$$\\text{CI} = \\bar{x} \\pm t^* \\cdot SE$$\n\nwhere:\n\n- $\\bar{x}$: sample mean (point estimate)\n- $t^*$: critical value from t-distribution (depends on confidence level and sample size; more details below)\n- $SE = \\frac{s}{\\sqrt{n}}$: standard error\n\n::: {.callout-note collapse=\"true\"}\n## Understanding Critical Values and the t-Distribution\n\nWhen we construct a confidence interval, we need to account for sampling variability. The **critical value** ($t^*$) tells us how many standard errors to extend on either side of our sample mean to achieve our desired confidence level.\n\n**Why the t-distribution?**\n\nFrom the sampling lecture, you know that the Central Limit Theorem tells us the sampling distribution of $\\bar{x}$ is approximately normal. If we *knew* the true population standard deviation $\\sigma$, we could use the standard normal distribution (also called $z$-distribution) for our critical values.\n\nHowever, in practice we almost never know $\\sigma$ but we estimate it with our sample standard deviation $s$. This estimation adds extra uncertainty. The **t-distribution** accounts for this additional uncertainty:\n\n- When $n$ is small, $s$ is an imprecise estimate of $\\sigma$ $\\rightarrow$ $t$-distribution has heavier tails than normal\n- When $n$ is large, $s$ becomes a good estimate of $\\sigma$ $\\rightarrow$ $t$-distribution approaches the normal distribution\n- The $t$-distribution has a parameter called **degrees of freedom** (df = $n-1$) that controls how close it is to normal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblue_col <- \"#00395B\"\nred_col <- \"#e65032\"\ngrey_col <- \"#6F6F6F\"\n\n# Create data for plotting\nx <- seq(-4, 4, length.out = 1000)\n\n# Plot 1: Small n (df = 2)\ndf_small <- 2\ndata_small <- data.frame(\n  x = x,\n  t_dist = dt(x, df = df_small),\n  normal = dnorm(x)\n)\n\np1 <- ggplot(data_small, aes(x = x)) +\n  geom_line(aes(y = t_dist, color = \"t-distribution\"), linewidth = 1) +\n  geom_line(aes(y = normal, color = \"Normal\"), linewidth = 1, linetype = \"dashed\") +\n  scale_color_manual(values = c(\"t-distribution\" = red_col, \"Normal\" = blue_col)) +\n  labs(\n    title = \"Small n (df = 2)\",\n    subtitle = \"Heavy tails: s is imprecise\",\n    x = NULL,\n    y = \"Density\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_blank(),\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(size = 10, color = grey_col)\n  ) +\n  ylim(0, 0.45)\n\n# Plot 2: Medium n (df = 10)\ndf_medium <- 10\ndata_medium <- data.frame(\n  x = x,\n  t_dist = dt(x, df = df_medium),\n  normal = dnorm(x)\n)\n\np2 <- ggplot(data_medium, aes(x = x)) +\n  geom_line(aes(y = t_dist, color = \"t-distribution\"), linewidth = 1) +\n  geom_line(aes(y = normal, color = \"Normal\"), linewidth = 1, linetype = \"dashed\") +\n  scale_color_manual(values = c(\"t-distribution\" = red_col, \"Normal\" = blue_col)) +\n  labs(\n    title = \"Medium n (df = 10)\",\n    subtitle = \"Approaching normal\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_blank(),\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(size = 10, color = grey_col)\n  ) +\n  ylim(0, 0.45)\n\n# Plot 3: Large n (df = 30)\ndf_large <- 30\ndata_large <- data.frame(\n  x = x,\n  t_dist = dt(x, df = df_large),\n  normal = dnorm(x)\n)\n\np3 <- ggplot(data_large, aes(x = x)) +\n  geom_line(aes(y = t_dist, color = \"t-distribution\"), linewidth = 1) +\n  geom_line(aes(y = normal, color = \"Normal\"), linewidth = 1, linetype = \"dashed\") +\n  scale_color_manual(values = c(\"t-distribution\" = red_col, \"Normal\" = blue_col)) +\n  labs(\n    title = \"Large n (df = 30)\",\n    subtitle = \"Nearly identical: s ≈ σ\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_blank(),\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(size = 10, color = grey_col)\n  ) +\n  ylim(0, 0.45)\n\n# Combine plots\ncombined_plot <- ggarrange(p1, p2, p3, \n                           ncol = 3, \n                           common.legend = TRUE, \n                           legend = \"bottom\")\n\n# Add overall title\nannotated_plot <- annotate_figure(\n  combined_plot,\n  top = text_grob(\"The t-distribution and the Normal\", \n                  face = \"bold\", size = 14)\n)\n\n# Display the plot\nprint(annotated_plot)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n**For confidence intervals:**\n\n- For a 95% CI, we want to capture the middle 95% of the sampling distribution\n- This leaves 2.5% in each tail (5% total)\n- The critical value $t^*$ marks the boundary points for these tails\n- In R: `qt(0.975, df = n-1)` gives us $t^*$ for a 95% CI (0.975 because we want the 97.5th percentile, leaving 2.5% in the upper tail)\n\n**The critical value depends on:**\n\n- **Confidence level:** Higher confidence $\\rightarrow$ larger $t^*$ $\\rightarrow$ wider interval\n- **Sample size (df):** Larger $n$ $\\rightarrow$ smaller $t^*$ $\\rightarrow$ narrower interval (approaches z-value)\n\n:::\n\n**For our customer spending example:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample data\nx_bar <- 250  # sample mean\ns <- 50       # sample standard deviation\nn <- 100      # sample size\n\n# Calculate standard error\nse <- s / sqrt(n)\n\n# Critical value for 95% confidence (df = n-1 = 99)\nt_star <- qt(0.975, df = 99)  # 0.975 because two-tailed\n\n# Margin of error\nmargin_of_error <- t_star * se\n\n# Confidence interval\nci_lower <- x_bar - margin_of_error\nci_upper <- x_bar + margin_of_error\n\n# Display results\nci_results <- data.frame(\n  Statistic = c(\"Standard Error\", \"Critical Value (t*)\", \"Margin of Error\", \n                \"Lower Bound\", \"Upper Bound\"),\n  Value = c(se, t_star, margin_of_error, ci_lower, ci_upper)\n)\nknitr::kable(ci_results, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Statistic           |  Value|\n|:-------------------|------:|\n|Standard Error      |   5.00|\n|Critical Value (t*) |   1.98|\n|Margin of Error     |   9.92|\n|Lower Bound         | 240.08|\n|Upper Bound         | 259.92|\n\n\n:::\n:::\n\n\nThe standard error is 5 EUR, and our 95% confidence interval is [240.08 EUR, 259.92 EUR].\n\n**Interpretation:** \"We are 95% confident that the true average monthly spending for all customers is between 240.08 EUR and 259.92 EUR.\"\n\n### 2.3 Understanding \"95% Confidence\"\n\nThis is one of the most commonly misunderstood concepts in statistics. Let's be very precise about what it means and doesn't mean.\n\n**What \"95% confidence\" DOES mean:**\n\n\"If we repeated this sampling process many times and constructed a 95% CI each time using the same procedure, approximately 95% of those intervals would contain the true population parameter.\"\n\nIt's a statement about the **long-run behavior of the procedure**, not about any single interval you've calculated.\n\n**The key insight:** The randomness is in the *sampling process* and therefore in which interval you get. The parameter $\\mu$ is fixed (though unknown). Before you draw your sample, the interval you'll get is random - it has a 95% probability of covering $\\mu$. After you've calculated it, that specific interval either covers $\\mu$ or it doesn't. And the true parameter $\\mu$ is never random!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIn this simulation, we drew 50 different samples and constructed a 95% CI for each. Notice that:\n\n- Most intervals (blue) contain the true mean $\\mu$ = 250\n- A few intervals (red) miss it—this is expected!\n- About 95% capture the true value (47 out of 50 in this simulation)\n\n**What \"95% confidence\" DOES NOT mean:**\n\n❌ **\"There's a 95% probability that $\\mu$ is in this interval\"**\n\n- No! Once you've calculated a specific interval (say, [240, 260]), the true parameter $\\mu$ is either in it (probability = 1) or not in it (probability = 0)\n- The parameter is fixed; it doesn't have a probability distribution\n- This would be a Bayesian credible interval, not a frequentist confidence interval\n\n❌ **\"I'm 95% sure the true value is in this interval\"**\n\n- This phrasing suggests subjective probability about $\\mu$\n- The 95% refers to the procedure's success rate, not your personal certainty\n- If forced to use this language, be clear you mean confidence in the method, not the specific interval\n\n❌ **\"95% of the data falls in this interval\"**\n\n- No! The CI is about the population parameter (mean), not individual data points\n- For that, you'd calculate: $\\bar{x} \\pm 2s$ (approximately)\n- These are two completely different concepts\n\n❌ **\"The interval [240, 260] has a 95% chance of containing $\\mu$**\n\n- No! This specific interval either does or doesn't contain $\\mu$\n- *Before* you calculated it, the random interval you were about to compute had a 95% probability\n- *After* calculation, no probability remains - it's determined (even though you don't know which)\n\n### 2.4 Factors Affecting Interval Width\n\nThe width of a confidence interval tells us about the precision of our estimate. Narrower is generally better (more precise).\n\n**Three factors determine width:**\n\n**1. Sample size (n):**\n- Larger $n$ $\\rightarrow$ smaller $SE$ $\\rightarrow$ narrower $CI$\n- Precision improves with $\\sqrt{n}$ (doubling $n$ doesn't double precision)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare CI width for different sample sizes\nsample_sizes <- c(25, 100, 400)\ns <- 50  # keep constant\n\nci_comparison <- data.frame(\n  n = sample_sizes,\n  SE = s / sqrt(sample_sizes),\n  Margin_Error = qt(0.975, sample_sizes - 1) * (s / sqrt(sample_sizes))\n)\n\nknitr::kable(ci_comparison, \n             digits = 2,\n             col.names = c(\"Sample Size\", \"Standard Error (€)\", \"Margin of Error (€)\"))\n```\n\n::: {.cell-output-display}\n\n\n| Sample Size| Standard Error (€)| Margin of Error (€)|\n|-----------:|------------------:|-------------------:|\n|          25|               10.0|               20.64|\n|         100|                5.0|                9.92|\n|         400|                2.5|                4.91|\n\n\n:::\n:::\n\n\nNotice how the margin of error decreases as sample size increases: from $\\pm$20.64 EUR with $n=25$ to $\\pm$4.91 EUR with $n=400$.\n\n**2. Variability (s):**\n- More variable population $\\rightarrow$ larger $SE$ $\\rightarrow$ wider $CI$\n- Can't control this, but larger samples help\n\n**3. Confidence level:**\n\n- So far we only talked about the 95% confidence interval\n- But we can increase or decrease the confidence level\n- Higher confidence $\\rightarrow$ wider interval\n- Trade-off between confidence and precision\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare CI width for different confidence levels\nconfidence_levels <- c(0.90, 0.95, 0.99)\nn <- 100\ns <- 50\n\nconf_comparison <- data.frame(\n  Confidence_Level = paste0(confidence_levels * 100, \"%\"),\n  Alpha = 1 - confidence_levels,\n  Critical_Value = qt(1 - (1 - confidence_levels)/2, n-1),\n  Margin_Error = qt(1 - (1 - confidence_levels)/2, n-1) * (s / sqrt(n))\n)\n\nknitr::kable(conf_comparison,\n             digits = 2,\n             col.names = c(\"Confidence Level\", \"α\", \"t*\", \"Margin of Error (€)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Confidence Level |    α|   t*| Margin of Error (€)|\n|:----------------|----:|----:|-------------------:|\n|90%              | 0.10| 1.66|                8.30|\n|95%              | 0.05| 1.98|                9.92|\n|99%              | 0.01| 2.63|               13.13|\n\n\n:::\n:::\n\n\nThe trade-off is clear: higher confidence requires a wider interval. At 90% confidence, the margin is $\\pm$8.3 EUR, while at 99% confidence it increases to $\\pm$13.13 EUR. But the gain we have with the 99% confidence interval is that we can be more confident about the interval containing the true parameter...\n\n**Key insight:** There's always a trade-off between confidence and precision. You can be more confident by making the interval wider, but that makes it less informative.\n\n### 2.5 Confidence Intervals in R\n\n**For a single mean:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using t.test() function\ncustomer_spending <- c(245, 267, 223, 289, 241, ...)  # your sample data\n\nresult <- t.test(customer_spending, conf.level = 0.95)\nresult$conf.int  # Extract the confidence interval\n```\n:::\n\n\n**For a proportion:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example: conversion rate from sample of 500 customers\n# 125 made a purchase\nprop.test(x = 125, n = 500, conf.level = 0.95)\n```\n:::\n\n\n**For regression coefficients (preview for regression lecture):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Confidence intervals are automatically included in regression output\nmodel <- lm(consumption ~ price, data = beer_data)\nconfint(model, level = 0.95)\n```\n:::\n\n\n### 2.6 Interpreting Confidence Intervals in Business Context\n\n**Example 1: Market Research**\n\nA company surveys 200 potential customers about willingness to pay for a new product.\n\n- Sample mean: 45 EUR\n- 95% CI: [42, 48] EUR\n\n**Good interpretation:** \"We're 95% confident that the average willingness to pay for all potential customers is between 42 and 48 EUR. This suggests a price point around 40-45 EUR would be reasonable.\"\n\n**Why this matters:** The interval helps with business decisions:\n\n- If production cost is 40 EUR, the lower bound (42 EUR) still provides margin\n- If cost is 50 EUR, even the upper bound (48 EUR) suggests unprofitability\n\n**Example 2: A/B Testing**\n\nAn e-commerce site tests two checkout designs:\n\n- Design A: 100 users, 23 conversions $\\rightarrow$ 23% (95% CI: [15%, 31%])\n- Design B: 100 users, 31 conversions $\\rightarrow$ 31% (95% CI: [22%, 40%])\n\n**Interpretation:** The intervals overlap substantially. While Design B has a higher point estimate, we can't confidently say it's better. The true conversion rates might be equal, or Design A might even be better (both plausible given the overlap).\n\n**Business decision:** Need more data before making a costly redesign decision.\n\n### 2.7 Preview: Relationship Between Confidence Intervals and Hypothesis Tests\n\nConfidence intervals and hypothesis tests are two sides of the same coin. They use the same underlying sampling distribution concepts but answer different questions:\n\n- **Hypothesis test:** \"Is the claim $\\mu$ = 250 compatible with my data?\"\n- **Confidence interval:** \"What values of $\\mu$ are compatible with my data?\"\n\n**Key connection:** A 95% confidence interval contains all values of $\\mu$ that would NOT be rejected in a two-sided hypothesis test at $\\alpha = 0.05$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThis connection is incredibly useful: you can often \"test\" hypotheses just by checking whether a claimed value falls inside the confidence interval!\n\n---\n\n## 3. Hypothesis Testing: Evaluating Claims\n\n### 3.1 The Logic of Hypothesis Testing\n\nHypothesis testing provides a formal framework for using sample data to evaluate claims about population parameters. Unlike confidence intervals, which give us a range of plausible values, hypothesis tests answer a specific yes/no question.\n\n**The fundamental question:** \"Is our sample data consistent with a specific claim about the population?\"\n\n#### The Courtroom Analogy\n\nThink of hypothesis testing like a trial:\n\n**Presumption of innocence** = **Null hypothesis ($H_0$)**\n\n- We assume the defendant (claim) is innocent (true) until proven guilty (false)\n- The burden of proof lies with the prosecution (the data)\n\n**Evidence** = **Sample data**\n\n- Must be strong enough to overcome presumption\n\n**Verdict** = **Decision**\n\n- \"Guilty\" = Reject $H_0$ (evidence strong enough)\n- \"Not guilty\" = Fail to reject $H_0$ (evidence insufficient)\n\n**Crucial point:** \"Not proven guilty\" ≠ \"innocent\"\n\n- Similarly, \"fail to reject $H_0 \\neq H_0$ is true\"\n- It only means we don't have strong enough evidence against it\n\n#### Example: Testing a Business Claim\n\nA coffee shop claims their average service time is 3 minutes. You observe 40 customers and find:\n\n- Sample mean: $\\bar{x} = 3.4$ minutes  \n- Sample SD: $s = 0.8$ minutes\n\n**Question:** Is the claim of $\\mu$ = 3 minutes consistent with your data?\n\n**Intuitive reasoning:**\n\n- Your sample mean (3.4) is higher than the claimed value (3.0)\n- But samples vary due to randomness. Maybe you just happened to observe slower customers?\n- How do we decide if 0.4 minutes difference is \"too large\" to be explained by chance alone?\n\nThis is exactly what hypothesis testing answers!\n\n### 3.2 The Five-Step Process\n\n#### Step 1: State the Hypotheses\n\nEvery hypothesis test requires two complementary statements:\n\n**Null Hypothesis ($H_0$):**\n\n- A specific claim we're testing\n- Usually represents \"no effect,\" \"no difference,\" or \"no change\"\n- Always includes an equality ($=$, $\\geq$, or $\\leq$)\n\n**Alternative Hypothesis ($H_1$ or $H_A$):**\n\n- What we suspect might be true\n- What we're trying to find evidence for\n- Can be one-sided or two-sided\n\n**For our coffee shop example:**\n\n- $H_0$: $\\mu=3$  (service time equals claimed value)\n- $H_1$: $\\mu \\neq 3$ (service time differs from claimed value)\n\n**Types of alternative hypotheses:**\n\n1. **Two-sided:** $H_1$: $\\mu \\neq  3$\n\n   - Used when we care about deviations in either direction\n   - \"Is the service time different from 3 minutes?\"\n\n2. **Right-sided:** $H_1$: $\\mu > 3$\n\n   - Used when we only care about increases\n   - \"Is the service time longer than 3 minutes?\"\n\n3. **Left-sided:** $H_1$: $\\mu < 3$\n\n   - Used when we only care about decreases  \n   - \"Is the service time shorter than 3 minutes?\"\n\n**Business example with all three types:**\n\nTesting a new website design's effect on conversion rates:\n\n- **Two-sided test:** \"Does the new design change conversion rates?\" ($H_1$: $\\mu \\neq \\mu_0$)\n  - Use when you're genuinely unsure of direction\n  \n- **Right-sided test:** \"Does the new design increase conversion rates?\" ($H_1$: $\\mu > \\mu_0$)\n  - Use when you're specifically trying to show improvement\n  \n- **Left-sided test:** \"Does the new design decrease bounce rates?\" ($H_1$: $\\mu < \\mu_0$)\n  - Use when you're testing for reduction in negative outcomes\n  \n::: {.callout-note collapse=\"true\"}\n## $>$ or $\\geq$ in the alternative hypothesis?\n\nYou should use strict inequality (greater than, not greater or equal to) for the\nformulation of the alternative hypothesis $H_1$!\n\nWhy? The null and alternative hypotheses must be mutually exclusive and exhaustive. \nThe standard approach is to assign the equality to $H_0$.\n\nFrom a practical standpoint, the exact boundary point has probability zero in continuous distributions, so whether you include the equality in $H_0$ or $H_1$ doesn't affect the test's behavior.\nBut the convention is to put it in $H_0$ for consistency with the testing framework.\n\n\n:::\n\n#### Step 2: Choose a Significance Level ($\\alpha$)\n\nThe **significance level** (alpha, $\\alpha$) is the threshold for how much evidence we require before rejecting $H_0$. It represents the probability of Type I error we're willing to accept.\n\n**Common choices:**\n\n- **$\\alpha = 0.05$:** Standard in most business/research contexts (5% risk of false positive)\n- **$\\alpha = 0.01$:** More conservative, used when Type I errors are costly\n- **$\\alpha = 0.10$:** More liberal, used in exploratory research\n\n**For our example:** $\\alpha = 0.05$ (we'll use the conventional threshold)\n\n::: {.callout-warning}\n## The $\\alpha = 0.05$ Convention\n\nThe choice of $\\alpha = 0.05$ is largely arbitrary, originating from Ronald Fisher's work in the 1920s. It's a convention, not a law of nature. The specific value should ideally depend on the costs of different types of errors in your specific context. More on this later when we discuss Type I and Type II errors.\n:::\n\n#### Step 3: Calculate the Test Statistic\n\nThe **test statistic** standardizes our sample evidence so we can compare it to a known probability distribution. For testing a mean, we use the t-statistic:\n\n$$t = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}$$\n\nComponents:\n\n- **Numerator:** How far is our sample mean from the claimed value $\\mu_0$?\n- **Denominator:** Standard error (expected sampling variation)\n- **Result:** Number of standard errors away from claimed value\n\n**For our coffee shop example:**\n\n::: {.cell}\n\n```{.r .cell-code}\nx_bar <- 3.4  # sample mean\nmu_0 <- 3.0   # claimed value\ns <- 0.8      # sample SD\nn <- 40       # sample size\n\n# Calculate test statistic\nse <- s / sqrt(n)\nt_stat <- (x_bar - mu_0) / se\n\n# Create results table\ntest_results <- data.frame(\n  Statistic = c(\"Standard Error\", \"Test Statistic (t)\"),\n  Value = c(se, t_stat)\n)\nknitr::kable(test_results, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Statistic          | Value|\n|:------------------|-----:|\n|Standard Error     | 0.126|\n|Test Statistic (t) | 3.162|\n\n\n:::\n:::\n\n\nThe standard error is 0.126 minutes, and our test statistic is $t = 3.162$.\n\n**Interpretation:** Our sample mean is 3.16 standard errors above the claimed mean. Is this unusual enough to doubt the claim?\n\n#### Step 4: Calculate the $p$-value\n\nThe **p-value** is the probability of observing a test statistic as extreme as (or more extreme than) what we actually observed, *assuming $H_0$ is true*.\n\n**Critical insight from sampling lecture:** Remember the sampling distribution? If $H_0$ is true ($\\mu = 3$), then our sample means would follow a $t$-distribution centered at $3$. The $p$-value tells us how far out in the tail our observed value sits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Degrees of freedom\ndf <- n - 1\n\n# P-value for two-sided test\np_value <- 2 * pt(abs(t_stat), df = df, lower.tail = FALSE)\n\n# Display result\npvalue_result <- data.frame(\n  Statistic = c(\"Degrees of Freedom\", \"P-value\"),\n  Value = c(df, p_value)\n)\nknitr::kable(pvalue_result, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Statistic          |  Value|\n|:------------------|------:|\n|Degrees of Freedom | 39.000|\n|P-value            |  0.003|\n\n\n:::\n:::\n\n\nWith $p=$ 0.003, we have very strong evidence against $H_0$.\n\n**Interpretation:** If the true average service time were actually 3 minutes, we would observe a sample mean as extreme as 3.4 minutes (or more extreme) only about 0.3% of the time due to random sampling variation alone.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n#### Step 5: Make a Decision\n\nCompare p-value to $\\alpha$:\n\n- **If p-value < $\\alpha$:** Reject $H_0$ (evidence is strong enough)\n- **If p-value \\geq $\\alpha$:** Fail to reject $H_0$ (evidence is insufficient)\n\n**For our example:** \n\n- $p$-value (0.003) < $\\alpha$ (0.05)\n- **Decision:** Reject $H_0$\n- **Conclusion:** There is strong evidence that the average service time differs from the claimed 3 minutes. The data suggest service times are longer than claimed.\n\n### 3.3 Understanding $p$-values\n\n$p$-values are among the most misunderstood concepts in statistics. Let's be very precise about what they mean and don't mean.\n\n#### What $p$-values ARE\n\n**Definition:** The $p$-value is the probability of observing data at least as extreme as what we actually observed, *if the null hypothesis were true*.\n\n**Key points:**\n\n- It's calculated *assuming* $H_0$ is true (not testing whether $H_0$ is true)\n- It measures how \"surprising\" or \"extreme\" our data are under $H_0$\n- It's a continuous measure of evidence (not binary)\n- Lower $p$-values indicate stronger evidence against $H_0$\n\n**Think of it as:**\n\n- A measure of compatibility between your data and $H_0$\n- How awkward it would be to maintain the null hypothesis given what you observed\n- The probability of getting \"unlucky\" with a sample if $H_0$ were true\n\n#### What $p$-values ARE NOT\n\n❌ **\"The probability that $H_0$ is true\"**\n\n- No! The $p$-value is calculated *assuming* $H_0$ is true\n- It can't tell you the probability that $H_0$ is true\n\n❌ **\"The probability that the result occurred by chance\"**\n\n- No! The result already occurred ($p = 1$ for that)\n- It's about how likely such results are under $H_0$\n\n❌ **\"The probability that you made a mistake\"**\n\n- No! That's related to Type I error ($\\alpha$), not the $p$-value\n- Confusing these is very common\n\n❌ **\"The size or importance of an effect\"**\n\n- No! Small effects can have tiny $p$-values with large samples\n- Large effects can have large $p$-values with small samples\n- $p$-values conflate effect size and sample size\n\n#### Common Misinterpretations - Business Examples\n\n**Scenario:** A marketing campaign test shows $p = 0.03$\n\n- **Wrong:** \"There's a 3% chance the campaign doesn't work.\"\n\n- **Right:** \"If the campaign truly had no effect, we'd see results this extreme only 3% of the time by chance alone.\"\n\n**Scenario:** Your analysis yields $p = 0.12$\n\n- **Wrong:** \"The effect doesn't exist.\"\n- **Right:** \"We don't have sufficient evidence to reject the hypothesis of no effect at $\\alpha = 0.05$. This could mean: no effect exists. But it could also mean: our sample size was too small to detect it.\"\n\n**Scenario:** One study finds $p = 0.04$, another finds $p = 0.06$\n\n- **Wrong:** \"The first study found an effect but the second didn't.\"\n\n- **Right:** \"Both studies found similar evidence. The first barely crossed an arbitrary threshold while the second barely didn't. The results are likely more similar than different.\"\n\n### 3.4 Types of Errors\n\nEvery hypothesis test can result in one of four outcomes, two of which are errors:\n\n|                          | **$H_0$ is True**           | **$H_0$ is False**          |\n|--------------------------|--------------------------|--------------------------|\n| **Reject $H_0$**            | **Type I Error** ($\\alpha$)     | Correct Decision (Power) |\n| **Fail to Reject $H_0$**    | Correct Decision         | **Type II Error** (\\beta)    |\n\n#### Type I Error (False Positive)\n\n**Definition:** Rejecting $H_0$ when it's actually true\n\n**Also called:** False positive, $\\alpha$-error\n\n**Probability:** $\\alpha$ (significance level)\n\n**Business example:** \nA pharmaceutical company concludes their new drug is effective when it actually isn't. They invest millions in production and marketing of an ineffective treatment.\n\n**Coffee shop example:**\nConcluding that service times differ from 3 minutes when they actually don't, leading to unnecessary process changes.\n\n#### Type II Error (False Negative)\n\n**Definition:** Failing to reject $H_0$ when it's actually false\n\n**Also called:** False negative, $\\beta$ error\n\n**Probability:** $\\beta$ (depends on effect size, sample size, and $\\alpha$)\n\n**Power:** 1 - $\\beta$ (probability of correctly rejecting a false $H_0$)\n\n**Business example:**\nA company fails to detect that a new training program actually does improve productivity, so they don't implement it company-wide, missing an opportunity for improvement.\n\n**Coffee shop example:**\nConcluding there's insufficient evidence that service times differ from 3 minutes when they actually do, missing a genuine service problem.\n\n#### Which Error is Worse?\n\nThis depends entirely on context! Consider the consequences:\n\n**Example 1: Quality Control**\n\n- $H_0$: Production process is working correctly\n- **Type I Error:** Stop production unnecessarily $\\rightarrow$ Costly but safe\n- **Type II Error:** Miss a defect problem $\\rightarrow$ Potentially dangerous\n- **Typical choice:** Accept higher $\\alpha$ (0.10) to minimize Type II errors\n\n**Example 2: New Product Launch**\n- $H_0$: New product won't be profitable\n- **Type I Error:** Launch unprofitable product $\\rightarrow$ Waste resources\n- **Type II Error:** Don't launch profitable product $\\rightarrow$ Missed opportunity\n- **Typical choice:** Balance depends on launch costs vs. opportunity costs\n\n**Example 3: Medical Diagnosis** (Classic example for intuition)\n- $H_0$: Patient is healthy\n- **Type I Error:** False positive $\\rightarrow$ Unnecessary anxiety/treatment\n- **Type II Error:** False negative $\\rightarrow$ Missed diagnosis\n- **Typical choice:** Depends on disease seriousness and treatment costs\n\n#### The Trade-off\n\nThere's a fundamental trade-off between Type I and Type II errors:\n\n- **Decrease $\\alpha$** (be more conservative) $\\rightarrow$ Fewer false positives but more false negatives\n- **Increase $\\alpha$** (be more liberal) $\\rightarrow$ Fewer false negatives but more false positives\n\n**The only way to reduce both:** Increase sample size!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n### 3.5 Common Hypothesis Tests\n\n#### One-Sample t-test\n\n**When to use:** Testing a claim about a single population mean\n\n**Requirements:**\n\n- One numerical variable\n- Random sample\n- Approximately normal distribution (or large sample, typically $n > 30$)\n\n**Example:** Employee Productivity\n\nA company claims average employee productivity is 85 units/day. You sample 50 employees:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate data\nset.seed(123)\nproductivity <- rnorm(50, mean = 82, sd = 12)\n\n# Perform one-sample t-test\nresult <- t.test(productivity, mu = 85, alternative = \"two.sided\")\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  productivity\nt = -1.6466, df = 49, p-value = 0.106\nalternative hypothesis: true mean is not equal to 85\n95 percent confidence interval:\n 79.25529 85.57039\nsample estimates:\nmean of x \n 82.41284 \n```\n\n\n:::\n:::\n\n\n**Interpreting output:**\n\n- **t-statistic:** -1.65 (sample mean is -1.65 $SE$ below claimed value)\n- **p-value:** 0.106 (if $\\mu = 85$, we'd see this difference in 10.6% cases)\n- **Decision:** At $\\alpha = 0.05$, fail to reject $H_0$ (insufficient evidence)\n- **95% CI:** [79.3, 85.6] (notice that 85 is inside the interval)\n\n**Business interpretation:** \"While the sample mean (82.4) is lower than the claimed value (85), the difference isn't statistically significant at the 5% level. We don't have strong evidence that the true productivity differs from 85 units/day. However, the $p$-value is small ($p = $ 0.106), suggesting we might want to collect more data or investigate further.\"\n\n#### Two-Sample t-test\n\n**When to use:** Comparing means between two independent groups\n\n**Requirements:**\n\n- One numerical outcome variable\n- One categorical grouping variable (two groups)\n- Independent groups (no overlap)\n- Random samples from each group\n\n**Example:** Marketing Campaign Effectiveness\n\nControl group (no email) vs. Treatment group (email campaign):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate data\nset.seed(456)\ncontrol <- rnorm(100, mean = 45, sd = 15)\ntreatment <- rnorm(100, mean = 55.5, sd = 15)\n\n# Perform two-sample t-test\nresult <- t.test(treatment, control, \n                 alternative = \"greater\",  # one-sided: treatment > control\n                 var.equal = FALSE)       # don't assume equal variances\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  treatment and control\nt = 3.3162, df = 197.82, p-value = 0.0005429\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n 3.481861      Inf\nsample estimates:\nmean of x mean of y \n 53.74937  46.80862 \n```\n\n\n:::\n:::\n\n\n**Interpreting output:**\n\n- **t-statistic:** 3.32 (sample mean is 3.32 $SE$ below claimed value)\n- **p-value:** 0.001 (if $\\mu = 85$, we'd see this difference in 0.1% cases)\n- **Decision:** Reject $H_0$ (treatment effect is real)\n- **95% CI:** [3.5, Inf]  (one-sided, so only lower bound)\n\n\n**Business interpretation:** \"Customers who received the email campaign spent significantly more (mean: 53.7 EUR) than those who didn't (mean: 46.8 EUR)). The difference of 6.9 EUR is statistically significant ($p < 0.001$), suggesting the campaign was effective. The 95% confidence interval suggests the true effect is at least 3.48 EUR.\"\n\n#### Important Variations\n\n**Paired t-test:** When observations are naturally paired\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example: Before-after measurements on same individuals\nbefore <- c(7.2, 6.8, 7.5, 6.9, 7.1)\nafter <- c(7.8, 7.2, 8.1, 7.4, 7.7)\n\nt.test(after, before, paired = TRUE)\n```\n:::\n\n\n**Welch's t-test vs. Student's t-test:**\n\n- `var.equal = FALSE` (default): Welch's test, doesn't assume equal variances (safer)\n- `var.equal = TRUE`: Student's t-test, assumes equal variances (slightly more powerful if true)\n\n**When in doubt:** Use Welch's (`var.equal = FALSE`) - it's more robust\n\n### 3.6 Connection to Regression (Preview for regression lecture)\n\nEverything you've learned about hypothesis testing directly applies to regression. In fact, regression output is dominated by hypothesis tests!\n\n**Every regression coefficient has a t-test:**\n\nFrom your the beer consumption example from the lecture:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term      | estimate| std_error| statistic| p_value|\n|:---------|--------:|---------:|---------:|-------:|\n|intercept |   86.406|     4.324|    19.982|       0|\n|price     |   -9.835|     1.375|    -7.151|       0|\n\n\n:::\n:::\n\n\n\n**What's being tested?**\n\n- $H_0$: $\\beta_1 = 0$ (price has no relationship with consumption)\n- $H_1$: $\\beta_1\\neq 0$ (price does affect consumption)\n\n**The test statistic** is calculated exactly like before:\n\n$$t = \\frac{\\hat{\\beta}_1 - 0}{SE(\\hat{\\beta}_1)} = \\frac{-9.84}{1.38} = -7.15$$\n\n**The p-value** of 0.000 means: \"If price truly had no effect on consumption, we would almost never see a coefficient this large (in absolute value) due to chance alone.\"\n\n**Interpretation:** \"There is extremely strong evidence that price is associated with beer consumption. For each 1 EUR increase in price, consumption decreases by an estimated 9.84 liters on average.\"\n\n**The key insight:** Understanding hypothesis testing now makes regression output immediately interpretable!\n\n---\n\n## 4. Statistical vs. Practical Significance\n\nOne of the most important lessons in applied statistics: **statistical significance $\\neq$ practical importance**\n\nThis is especially critical in business contexts where you must make decisions, not just detect effects.\n\n#### The Problem with Large Samples\n\nWith very large samples, even tiny, meaningless effects become statistically significant:\n\n**Example:** Website A/B Test\n\nImagine a large e‑commerce platform selling a popular gadget for 50 EUR.\nManagement wants to test increasing the price to 50.10 EUR (a 0.2% increase) and runs an A/B test: half the visitors see 50 EUR, half see 50.10 EUR.​\n\n- Control group (50 EUR): conversion rate = 5.00%\n- Treatment group (50.10 EUR): conversion rate = 4.90%\n\nThe absolute difference in conversion is only 0.02 percentage points, which is economically negligible: revenue per visitor stays almost identical, and the 10‑cent higher price barely changes total profit once marketing and operating costs are considered.​\n\nNow assume the platform has 5 million visitors in each group during the test.\nWith 5,000,000 visitors per variant, the standard error of the difference in proportions becomes extremely small, so a tiny difference in conversion rate is enough to produce a very large z‑statistic and a p‑value far below 0.001:\n\n- **Statistically**: the null \"no difference in conversion\" is rejected with overwhelming significance because, with such huge $n$, even tiny deviations from equality are detected.\n\n- **Practically**: the effect size (difference in conversion and impact on profit per visitor) is essentially zero, so changing the price by 0.10 EUR has no meaningful business impact.\n\n::: {.callout-note collapse=\"true\"}\n## Simulation example: large $n$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Parameters\np_control   <- 0.0500   # 5.00% conversion\np_treatment <- 0.0490   # 4.90% conversion\nn_per_group <- 5e6      # 5,000,000 visitors per variant\n\n# Simulate conversions (Bernoulli)\ncontrol_conv   <- rbinom(1, size = n_per_group, prob = p_control)\ntreatment_conv <- rbinom(1, size = n_per_group, prob = p_treatment)\n\n# Observed conversion rates\ncontrol_rate   <- control_conv   / n_per_group\ntreatment_rate <- treatment_conv / n_per_group\n\nc(control_rate = control_rate,\n  treatment_rate = treatment_rate,\n  diff = treatment_rate - control_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  control_rate treatment_rate           diff \n     0.0499132      0.0489280     -0.0009852 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Two-sample proportion test (approximate z-test)\ntest_large <- prop.test(\n  x    = c(control_conv, treatment_conv),\n  n    = c(n_per_group, n_per_group),\n  correct = FALSE\n)\n\ntest_large$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.624199e-13\n```\n\n\n:::\n\n```{.r .cell-code}\ntest_large\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(control_conv, treatment_conv) out of c(n_per_group, n_per_group)\nX-squared = 51.653, df = 1, p-value = 6.624e-13\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.0007165263 0.0012538737\nsample estimates:\n   prop 1    prop 2 \n0.0499132 0.0489280 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Alternative example: small $n$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Parameters\np_control   <- 0.0500   # 5.00% conversion\np_treatment <- 0.0490   # 4.90% conversion\nn_per_group <- 500      # 500 visitors per variant\n\n# Simulate conversions (Bernoulli)\ncontrol_conv   <- rbinom(1, size = n_per_group, prob = p_control)\ntreatment_conv <- rbinom(1, size = n_per_group, prob = p_treatment)\n\n# Observed conversion rates\ncontrol_rate   <- control_conv   / n_per_group\ntreatment_rate <- treatment_conv / n_per_group\n\nc(control_rate = control_rate,\n  treatment_rate = treatment_rate,\n  diff = treatment_rate - control_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  control_rate treatment_rate           diff \n         0.044          0.056          0.012 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Two-sample proportion test (approximate z-test)\ntest_large <- prop.test(\n  x    = c(control_conv, treatment_conv),\n  n    = c(n_per_group, n_per_group),\n  correct = FALSE\n)\n\ntest_large$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3839882\n```\n\n\n:::\n\n```{.r .cell-code}\ntest_large\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(control_conv, treatment_conv) out of c(n_per_group, n_per_group)\nX-squared = 0.75789, df = 1, p-value = 0.384\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.039006  0.015006\nsample estimates:\nprop 1 prop 2 \n 0.044  0.056 \n```\n\n\n:::\n:::\n\n:::\n\n\nConversely, with small samples, even large, important effects may not reach statistical significance!\n\n> There are tools to standardize effect sizes to make them easier comparable, such as Cohen's d. \nWe will learn more about these tools in the lecture on analyzing experimental data!\n\n\n## 5. Common Pitfalls and Best Practices\n\n### 5.1. Common pitfalls\n\n#### Pitfall 1: \"$p = 0.05$ is a magical threshold\"\n\n**Wrong thinking:** \n- $p = 0.049 \\rightarrow$ \"Significant! The effect exists!\"\n- $p = 0.051 \\rightarrow$ \"Not significant! No effect!\"\n\n**Better thinking:**\n- Both results show similar evidence\n- The threshold $\\alpha = 0.05$ is arbitrary\n- Focus on effect sizes and confidence intervals\n- Consider the entire body of evidence\n\n**Example:** \nTwo studies test same intervention:\n\n- Study 1: $p = 0.048$, effect = +5 units\n- Study 2: $p = 0.052$, effect = +5.2 units\n\nThese findings are essentially identical! Don't overinterpret the threshold.\n\n#### Pitfall 2: \"Non-significant means no effect\"\n\n**Wrong thinking:**\n\"We found $p = 0.23$, so there's no relationship between X and Y.\"\n\n**Better thinking:**\n\"We found insufficient evidence to reject the null hypothesis. This could mean:\n- No effect exists (true negative)\n- An effect exists but our sample was too small to detect it (false negative)\n- Our measurement was too noisy\"\n\n**How to improve:**\n- Report the confidence interval: \"The effect could range from -2 to +8\"\n- Consider practical equivalence testing\n\n#### Pitfall 3: \"p-value measures importance\"\n\n**Wrong thinking:**\n- $p = 0.001$ is \"highly significant\" $\\rightarrow$ effect must be important\n- $p = 0.04$ is \"barely significant\" $\\rightarrow$ effect is probably not important\n\n**Better thinking:**\n\n- $p$-value = f(effect size, sample size, variability)\n- Can have $p < 0.001$ with tiny, meaningless effect (large $n$)\n- Can have $p = 0.10$ with large, important effect (small $n$)\n- Always report effect size separately!\n\n#### Pitfall 4: Confusing confidence interval interpretation\n\n**Wrong:** \"There's a 95% probability that $\\mu$ is in [50, 60]\"\n\n**Right:** \"We're 95% confident that $\\mu$ is in [50, 60]\"\n\n**Even better:** \"If we repeated this study many times, 95% of our confidence intervals would contain the true population mean\"\n\n### 5.2 When NOT to Use Hypothesis Testing\n\nHypothesis testing is not always the right tool. Here are situations where alternatives are better:\n\n#### Situation 1: You Have the Full Population\n\n**Example:** Analyzing all transactions from your company database\n\n- No sampling uncertainty → no need for inferential statistics\n- Descriptive statistics (means, proportions) are exact\n- Focus on practical importance, not statistical significance\n\n**What to do instead:** Report actual differences, visualize patterns, calculate business metrics (ROI, etc.)\n\n#### Situation 2: The Decision Doesn't Depend on Statistical Evidence\n\n**Example:** Choosing between two supplier bids\n\n- Bid A: 100,000 EUR\n- Bid B: 120,000 EUR\n\nYou don't need a hypothesis test to know B costs more! The decision depends on:\n\n- Quality considerations\n- Reliability\n- Relationship factors\n- Risk assessment\n\n**What to do instead:** Multi-criteria decision analysis, cost-benefit analysis\n\n#### Situation 3: Effect Sizes Matter More Than Existence\n\n**Example:** Comparing two marketing strategies\n\nEven if Strategy B is \"significantly better\" ($p < 0.05$), you need to know:\n\n- **How much better?** (Effect size)\n- **What's the range of plausible values?** (Confidence interval)\n- **What's the business impact?** (Revenue, costs, ROI)\n\n**What to do instead:** Focus on estimation and confidence intervals rather than testing\n\n#### Situation 4: Data Quality is Poor\n\n**Example:** Survey with 10% response rate and clear selection bias\n\nNo amount of statistical testing fixes:\n\n- Non-representative samples\n- Measurement error\n- Missing data\n- Biased data collection\n\n**What to do instead:** \n\n- Acknowledge limitations\n- Use sensitivity analysis\n- Triangulate with other data sources\n- Focus on improving data quality\n\n#### Situation 5: Exploratory Data Analysis\n\n**Example:** Initial investigation of customer behavior patterns\n\nWhen you're:\n\n- Generating hypotheses (not testing them)\n- Looking for patterns and insights\n- Building understanding of your data\n\n**What to do instead:**\n\n- Descriptive statistics and visualization\n- Data mining / pattern detection\n- Use findings to design proper confirmatory studies\n\n---\n\n## 7. Summary and Key Takeaways\n\n### Core Concepts Recap\n\n**Confidence Intervals:**\n\n- Provide a range of plausible values for a parameter\n- 95% confidence means the procedure works 95% of the time\n- Width depends on: sample size, variability, confidence level\n- More informative than point estimates alone\n\n**Hypothesis Testing:**\n\n- Formal framework for evaluating claims about populations\n- Uses sampling distributions to quantify evidence\n- P-values measure compatibility with $H_0$, not probability of $H_0$\n- Two types of errors: Type I ($\\alpha$) and Type II ($\\beta$)\n\n**The Connection:**\n\n- Both use sampling distributions and standard errors\n- A 95% CI contains all values that wouldn't be rejected at $\\alpha = 0.05$\n- Together they provide comprehensive picture of inference\n\n### Critical Thinking Points\n\n**1. Statistical significance ≠ Practical importance**\n\n- Large samples make tiny effects significant\n- Small samples may miss important effects\n- Always consider effect size and business impact\n\n**2. P-values are easily misinterpreted**\n\n- Not the probability $H_0$ is true\n- Not the probability of a mistake\n- Not a measure of effect size\n- Continuous measure of evidence, not binary threshold\n\n**3. Context matters enormously**\n\n- Which error (Type I or II) is more serious?\n- What's the cost of being wrong?\n- What's the minimum meaningful effect size?\n\n**4. Not every question needs a hypothesis test**\n\n- Sometimes estimation (CI) is more useful\n- Sometimes descriptive statistics suffice\n- Sometimes business judgment trumps statistics\n\n---\n\n## 8. Practice Questions\n\nTest your understanding with these questions. Think carefully about each one before looking at answers.\n\n### Conceptual Questions\n\n**1. Sample-Population Connection**\n\nYou survey 200 customers and find average satisfaction of 7.8/10 with a 95% CI of [7.5, 8.1]. Your colleague says: \"Great! We know that 95% of all customers have satisfaction between 7.5 and 8.1.\"\n\nWhat's wrong with this interpretation? What should they say instead?\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**What's wrong:**\nThe colleague is confusing the confidence interval for the *population mean* with the range where *individual data points* fall. The CI [7.5, 8.1] is about where we expect the *average* satisfaction to be, not where individual customer scores fall.\n\n**Correct interpretation:**\n\"We are 95% confident (using a procedure with a 95% success rate) that the true *average* satisfaction across all customers is between 7.5 and 8.1.\"\n\n**Additional clarification:**\nIf they want to know where 95% of individual customers' scores fall, they would need to calculate something like $\\bar{x} \\pm 2s$ (approximately), which would be much wider than the confidence interval for the mean.\n:::\n\n**2. P-value Interpretation**\n\nA marketing test yields $p = 0.08$ at $\\alpha = 0.05$. Your manager says: \"The test failed. There's no effect.\"\n\nWhat's problematic about this conclusion? What would be a better interpretation?\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**Problems with the manager's statement:**\n\n1. \"The test failed\" - The test didn't fail; it worked properly. We just didn't find sufficient evidence to reject $H_0$ at the predetermined threshold.\n2. \"There's no effect\" - Absence of statistical significance doesn't mean absence of an effect. It could mean:\n   - There truly is no effect (but we can't conclude this)\n   - There is an effect but our sample was too small to detect it (low power)\n   - There is an effect but it's smaller than we can reliably detect with this sample size\n\n**Better interpretation:**\n\n\"At the conventional $\\alpha = 0.05$ level, we don't have sufficient statistical evidence to conclude there's an effect. However, with $p = 0.08$, we're borderline. This suggests we should:\n1. Consider the effect size and confidence interval (not just the p-value)\n2. Look at the practical significance of any observed difference\n3. Consider collecting more data if the decision is important\n4. Not definitively conclude there's *no* effect\"\n\n**Additional considerations:**\n\n- The $p = 0.08$ vs. $p = 0.05$ distinction is somewhat arbitrary\n- If the effect size is meaningful in business terms, it might still be worth acting on\n- Should report: \"We observed [describe effect], but this didn't reach conventional statistical significance ($p = 0.08$)\"\n:::\n\n\n**3. Statistical vs. Practical**\n\nStudy A: $n = 50$, effect = 15%, $p = 0.08$\nStudy B: $n = 50,000$, effect = 0.5%, $p = 0.001$\n\nWhich finding is more likely to be useful in business? Why?\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**Study A is more likely to be useful** despite not being \"statistically significant.\"\n\n**Reasoning:**\n\n- **Study A:** 15% effect is substantial and practically meaningful. The $p = 0.08$ suggests marginal statistical evidence, likely due to small sample size ($n = 50$). The large effect size suggests this could have real business impact.\n  \n- **Study B:** 0.5% effect is tiny and likely not worth implementing even though it's \"highly significant\" ($p = 0.001$). The tiny p-value is due to the massive sample size ($n = 50,000$), which can detect even trivial differences.\n\n**Business decision framework:**\n\n1. **For Study A:** The 15% improvement could be worth investigating further with a larger sample to confirm. Even if true effect is smaller (say 10%), it might be valuable.\n   \n2. **For Study B:** Even if we're certain the effect exists (which $p = 0.001$ suggests), a 0.5% improvement rarely justifies implementation costs, training, and change management.\n\n**Key lesson:** Large samples make small effects significant; small samples might miss large effects. Always consider effect size and practical significance alongside $p$-values.\n:::\n\n\n**5. Type I vs. Type II**\n\nYour company is testing a new quality control procedure:\n- $H_0$: Product quality meets standards\n- $H_1$: Product quality below standards\n\nWhich type of error is more serious for:\n\na) A medical device manufacturer?\nb) A toy company?\nc) A car manufacturer?\n\nExplain your reasoning.\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**First, let's clarify what each error means in this context:**\n\nWith $H_0$: Quality meets standards and $H_1$: Quality below standards:\n- **Type I error:** Concluding quality is below standards when it actually meets them (false alarm)\n- **Type II error:** Concluding quality meets standards when it's actually below them (missed defect)\n\n**a) Medical device manufacturer:**\n\n**Type II error is more serious** (failing to detect a quality problem when one exists)\n\n- **Type I error (false positive):** Stopping production or recalling devices unnecessarily → Costly but safe\n- **Type II error (false negative):** Missing a defect that could harm patients → Potentially fatal, huge liability, regulatory issues\n\n**Decision:** Use higher $\\alpha$ (e.g., 0.10) to reduce Type II error rate. Better to be overly cautious.\n\n**b) Toy company:**\n\n**Type II error is more serious** (but less critical than medical devices)\n\n- **Type I error:** Unnecessary recalls/production stops → Costly\n- **Type II error:** Defective toys reach children → Safety risk, liability, reputation damage, potential regulatory action\n\n**Decision:** Use standard or slightly higher $\\alpha$ (0.05-0.10). Safety-critical but consequences less severe than medical devices.\n\n**c) Car manufacturer:**\n\n**Type II error is more serious** (missing safety-critical defects)\n\n- **Type I error:** Unnecessary production halts → Very expensive but safer\n- **Type II error:** Safety defects in vehicles → Potential accidents, deaths, massive recalls, legal liability, brand damage\n\n**Decision:** Use higher $\\alpha$ (0.10) for safety-critical components. Cost of false positives is preferable to risk of defective vehicles.\n\n**General principle:** When safety is at stake, minimize Type II errors (false negatives) even if it means more false positives. When only money is at risk, can balance both error types more evenly based on relative costs.\n:::\n\n### Practical Questions\n\n**6. Computing Confidence Intervals**\n\nA sample of 64 employees shows:\n\n- Mean productivity: 85 units/day\n- Standard deviation: 16 units/day\n\nCalculate and interpret:\n\na) Standard error\nb) 95% confidence interval for the mean\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**a) Standard error:**\n$$SE = \\frac{s}{\\sqrt{n}} = \\frac{16}{\\sqrt{64}} = \\frac{16}{8} = 2 \\text{ units/day}$$\n\n**b) 95% confidence interval:**\n\nFirst, find critical value: $t_{63, 0.975} \\approx 2.00$ (with $df = 63$)\n\nMargin of error: $ME = t^* \\times SE = 2.00 \\times 2 = 4$ units/day\n\nConfidence interval: $85 \\pm 4 = [81, 89]$ units/day\n\n**Interpretation:**\n\"Using a procedure that works 95% of the time, we estimate that the true average productivity for all employees is between 81 and 89 units per day. The margin of error is ±4 units/day.\"\n\n**Practical meaning:**\nIf company targets are based on 80 units/day, we can be quite confident (since even the lower bound is 81) that average productivity exceeds this target.\n:::\n\n**7. Hypothesis Test**\n\nA coffee shop claims average service time is 3 minutes. You observe 36 customers:\n\n- Sample mean: 3.5 minutes\n- Sample SD: 1.2 minutes\n\na) State appropriate hypotheses (two-sided)\nb) Calculate the test statistic\nc) Would you reject $H_0$ at $\\alpha = 0.05$? (Critical value: $t_{35} = 2.03$)\nd) What's your business conclusion?\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**a) Hypotheses:**\n- $H_0: \\mu = 3$ (claimed service time is correct)\n- $H_1: \\mu \\neq 3$ (actual service time differs from claim)\n\n**b) Test statistic:**\n$$t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}} = \\frac{3.5 - 3.0}{1.2/\\sqrt{36}} = \\frac{0.5}{0.2} = 2.5$$\n\n**c) Decision:**\n$|t| = 2.5 > 2.03$ (critical value), so **reject $H_0$**\n\nAlternatively, for two-sided test: $p$-value $= 2 \\times P(T > 2.5) \\approx 0.017 < 0.05$\n\n**d) Business conclusion:**\n\"There is statistically significant evidence ($p \\approx 0.017$) that actual service times differ from the claimed 3 minutes. The sample suggests service times average 3.5 minutes—about 30 seconds longer than claimed. \n\n**Recommendation:** The coffee shop should either:\n\n1. Update their claim to reflect reality (3.5 minutes)\n2. Investigate why service takes longer than expected\n3. Implement changes to reduce service time to meet the 3-minute target\n\nA 95% CI would be approximately [3.1, 3.9] minutes, suggesting the true average is at least 3.1 minutes—still notably above the claim.\"\n:::\n\n**8. Two-Sample Comparison**\n\n\nYou compare two training methods:\n\n- Method A: $n = 40$, mean = 78, SD = 12\n- Method B: $n = 40$, mean = 82, SD = 12\n\nThe 95% CI for the difference (B - A) is [-1, 9].\n\na) What does this interval tell you about statistical significance?\nb) If training costs are similar, which method should you use?\nc) What additional information would help your decision?\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n**a) Statistical significance:**\nThe confidence interval [-1, 9] **includes zero**, which means the difference is **not statistically significant** at $\\alpha = 0.05$ level. We cannot confidently say Method B is better than Method A based on this data alone.\n\n**Interpretation:** The true difference could plausibly be anywhere from -1 (Method A slightly better) to +9 (Method B notably better). Zero difference is within this range.\n\n**b) Which method to use:**\nGiven similar costs, there are two reasonable approaches:\n\n1. **Conservative approach:** Use Method A (current standard) since we haven't proven B is better. Don't change without clear evidence.\n\n2. **Optimistic approach:** Use Method B since the point estimate suggests it's 4 points better, and the worst plausible scenario (lower CI bound = -1) shows minimal downside risk.\n\n**Practical recommendation:** Since the confidence interval is mostly positive [only extends slightly negative], and point estimate favors B, Method B is reasonable to try—especially given similar costs and limited downside risk.\n\n**c) Additional helpful information:**\n\n1. **Sample size justification:** Can we collect more data? With $n = 40$ per group, power might be too low to detect meaningful differences\n2. **Effect size context:** Is a 4-point improvement meaningful for business outcomes? What do these scores represent?\n3. **Cost details:** Are there hidden costs (time, implementation, disruption)?\n4. **Practical constraints:** Implementation difficulty, scalability, employee preferences\n5. **Secondary outcomes:** Do methods differ on other important metrics (retention, engagement, long-term learning)?\n6. **Variance in effects:** Do some employee subgroups benefit more from one method?\n\n**Power consideration:** With SD = 12 and $n = 40$ per group, this study may have had only ~40% power to detect a 4-point difference. More data could clarify the picture.\n:::\n\n---\n\n\n::: {.callout-note icon=false}\n## Your Feedback Matters\n\nThis recap session is designed to be maximally useful for your learning. If you find sections confusing, would like more examples on specific topics, or have suggestions for improvement, please share your feedback. The goal is to make these concepts accessible and practical for your work in management and business.\n:::\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}