#!/usr/bin/env bash
# Regenerate _inter.scss: the five Inter woff2 files as base64 data URIs.
#
# Why base64 rather than url("assets/fonts/…")? A url() inside a reveal.js
# *theme* SCSS is resolved relative to the compiled theme in site_libs/, not
# relative to the .qmd — so relative paths are silently dropped and the deck
# falls back to a system sans. Data URIs have no path to resolve, so the font
# works when the deck is served from the site, opened from disk, or presented
# with no network.
#
# Run from this directory after replacing any of the woff2 files:
#     ./make-inter-scss.sh
set -euo pipefail
cd "$(dirname "$0")"

OUT=_inter.scss

{
  echo "// GENERATED by make-inter-scss.sh — do not edit by hand."
  echo "// Inter (SIL OFL 1.1), latin subset, from @fontsource/inter v5."
  echo "// Licence: LICENSE-Inter.txt in this directory."
  echo
} > "$OUT"

emit() { # weight style file
  local weight="$1" style="$2" file="$3"
  {
    echo "@font-face {"
    echo "  font-family: \"Inter\";"
    echo "  font-style: $style;"
    echo "  font-weight: $weight;"
    echo "  font-display: block;"
    printf '  src: url("data:font/woff2;base64,%s") format("woff2");\n' "$(base64 < "$file" | tr -d '\n')"
    echo "}"
    echo
  } >> "$OUT"
}

emit 400 normal inter-latin-400-normal.woff2
emit 400 italic inter-latin-400-italic.woff2
emit 500 normal inter-latin-500-normal.woff2
emit 600 normal inter-latin-600-normal.woff2
emit 700 normal inter-latin-700-normal.woff2

echo "wrote $OUT ($(du -h "$OUT" | cut -f1))"
