---
title: "🗓️ Session 6: Importing data"
date: "2026-10-30"
date-modified: last-modified
---

This is also one of the most underestimated topics. This session builds
upon the previous session on setting up a project environment. Now you will learn
how to import data obtained elsewhere into R. We focus on importing `.csv` files,
but with the skills acquired in this context you will face no difficulties in
importing other data types as well. 


## 👨‍🏫 Lecture Slides 

Either click on the slide area below or click 
[here](/content/material/slides/E5-DataImport.pdf) to download the slides.


```{=html}
<div class="embed-container">
  <iframe 
  src="/content/material/slides/E5-DataImport.pdf" 
  style="border: 0.5px" 
  width="80%"
  height="80%"
  ></iframe>
</div>
```

- [Data for the exercises](/content/material/fread_expls.zip)

## 🎥 Lecture videos 

All the videos are available via this [playlist](https://www.youtube.com/playlist?list=PLZDawQMrG1RK05hizCTxDROrbvdACAy0h).


```{=html}
<div class="embed-container">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/videoseries?si=jQeCMrsHboEtQDJD&amp;list=PLZDawQMrG1RK05hizCTxDROrbvdACAy0h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
```


## 📚 Mandatory Reading

- The tutorial [Importing and exporting data using data.table](/content/tutorials/importing-exporting-data/index.qmd) 


## ✍️ Coursework

- Do the exercises `ImportData` from the `DataScienceExercises` package

::: {.callout-tip collapse="true"}
## Quick code for starting the exercises
```{r}
#| eval: false
learnr::run_tutorial(
  name = "ImportData", 
  package = "DataScienceExercises", 
  shiny_args=list("launch.browser"=TRUE))
```
:::

