---
title: "🗓️ Session 8: Data visualization"
date: "2026-11-13"
date-modified: last-modified
---

One area for which R is particulary well-known for is the area of 
*visualization*. This is particularly because of the package 
[ggplot2](https://ggplot2.tidyverse.org/). 
This session introduces `ggplot2` and the general approach to generate 
visualization in R. The good thing is that if you follow the approach described
here, you can basically create every visualization type you can think of.


## 👨‍🏫 Lecture Slides 

Either click on the slide area below or click 
[here](/content/material/slides/E7-Visualization.pdf) to download the slides.


```{=html}
<div class="embed-container">
  <iframe 
  src="/content/material/slides/E7-Visualization.pdf" 
  style="border: 0.5px" 
  width="80%"
  height="80%"
  ></iframe>
</div>
```

<!--- The R script of this session is made available here after the session.
::: {.callout-tip collapse="true"}
## The R script of this session
<script src="https://gist.github.com/graebnerc/a3c11735652a0e4927ec71d4efadce09.js"></script>
:::
--->

## 🎥 Lecture videos 

All the videos are available via this [playlist](https://youtube.com/playlist?list=PLZDawQMrG1RL_OhYImHUM-F9rHsizLxYx&si=ofMKoYwusOS38sZL).

```{=html}
<div class="embed-container">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/videoseries?si=ofMKoYwusOS38sZL&amp;list=PLZDawQMrG1RL_OhYImHUM-F9rHsizLxYx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
```


## 📚 Mandatory Reading

- The tutorial [visualization](/content/tutorials/visualization/index.qmd)

## Further Reading

- @hadleygraphics, who introduces the theory underlying `ggplot2`
- [ggplot2 cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/data-visualization.pdf)
- Browse the website [from Data to Viz](https://www.data-to-viz.com/) and try to re-create some of the figures yourself

## ✍️ Coursework

- Do the exercises `Visualization1` from the `DataScienceExercises` package

::: {.callout-tip collapse="true"}
## Quick code for starting the exercises
```{r}
#| eval: false
learnr::run_tutorial(
  name = "Visualization1", 
  package = "DataScienceExercises", 
  shiny_args=list("launch.browser"=TRUE))
```
:::
