{
  "hash": "56723415e0d9ad58dc989bf2d01e31df",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logarithms: a gentle introduction\" # Also check out line 43\ndate: '2025-12-08'\ndocumentclass: scrartcl\nexecute: \n  freeze: auto\nformat: \n  html: # Settings set in _metadata.yml\n    toc: true\n  pdf:\n    include-in-header: \n      text: |\n        \\usepackage{lmodern} \n        \\usepackage{graphicx}\n        \\usepackage{hyperref}\n        \\usepackage{url}                \n        \\usepackage{xcolor}\n        \\usepackage{booktabs}\n        \\usepackage{listings}\n        \\lstloadlanguages{R}\n        \n        \\definecolor{eufblue}{RGB}{0,57,91}\n        \\definecolor{eufgrey}{RGB}{111,111,111}\n        \\definecolor{euflightblue}{RGB}{105,170,205}\n        \n        \\hypersetup{\n        pdfauthor={Claudius Graebner-Radkowitsch}\n        colorlinks=true,\n        linkcolor=euflightblue,\n        urlcolor=euflightblue\n        }\n        \\usepackage[includehead,includefoot,top=2cm, bottom=1.5cm]{geometry}\n        \\usepackage[headsepline, footsepline]{scrlayer-scrpage}\n        \\pagestyle{scrheadings}\n        \\clearpairofpagestyles\n        \\ihead{Tutorial: Logarithms}\n        %\\chead{Kopfzeile Mitte}\n        \\ohead{\\pagemark} %\n        \\ifoot{}\n        \\cfoot{\\href{https://researchmethodology-fall26.netlify.app/}{\\normalfont\\color{eufblue}{Data Science Using R - Fall Semester 2026}}} % Fußzeile Mitte\n        \\ofoot{} \n        \\setkomafont{disposition}{\\color{eufblue}\\bfseries}\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"R Packages\"}\nlibrary(tibble)\nlibrary(ggplot2)\nlibrary(moderndive)\nlibrary(ggpubr)\nlibrary(kableExtra)\n```\n:::\n\n\n\n## What are logarithms?\n\nA logarithm is simply a way of asking: \"To what power must I raise one number to get another number?\" \n\nFor example, if we ask \"what is the logarithm of 100 in base 10?\", we're really asking: \"10 raised to what power gives us 100?\" The answer is 2, because $10^2=100$.\n\nWe write this as: \n\n$$\\log_{10}\\left(100\\right)=2$$\n\nWe say this out loud as: \"log base 10 of 100 equals 2\"\n\n### Understanding the base of a logarithm\n\nThe **base** of a logarithm is the number we're repeatedly multiplying. In $\\log_{10}\\left(100\\right)=2$, the base is $10$. This tells us \"10 multiplied by itself 2 times equals 100.\"\n\nDifferent bases are useful in different contexts:\n\n- **Base 10** ($\\log_{10}$ or just \"log\"): Common in sciences, easy to interpret because we use base-10 number system\n- **Base 2** ($\\log_{2}$): Used in computer science and information theory as computers work with binary numbers ($0$ and $1$) and, thus, the base-2 number system\n- **Base *e*** ($\\ln$ or natural log): Most common in statistics, economics and business studies (see below)\n\n> **Convention:** When someone writes $\\log\\left(x\\right)$ without specifying a base, they usually mean the natural logarithm (base *e*) in statistics, although $\\ln$ would be more correct. This is particular confusing as in many other fields it might also mean the base 10.\n\nComputing logs in R is pretty straightforward:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog10(100)  # Base 10: \"log base 10 of 100\"\nlog2(8)     # Base 2: \"log base 2 of 8\" (2^3 = 8, so answer is 3)\nlog(100)    # Natural log (base e): \"natural log of 100\" or \"ln of 100\"\n```\n:::\n\n\nFrom the definition of the log the following special cases also follow naturally:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -Inf\n```\n\n\n:::\n:::\n\n\nand \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog(-1) # negative logs are not defined.\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NaN\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n## Business Example: Understanding Bases\n\nImagine you're analyzing company growth rates:\n\n- If your company **doubles** every year (2x growth), base-2 logarithms are useful: \n$\\log_{2}\\left(16\\right)=4$\nmeans \"we doubled 4 times to reach 16x our starting size\"\n- If your company grows by **10x** at each stage (startup → local → regional → national → international), base-10 logarithms make sense sense: $\\log_{10}\\left(1000\\right)=3$ then means that we grow by $10x$ three times to reach $1000x$ of our starting size.\n- If your company grows at a **continuous rate** (like 15% per year compounded continuously), natural logarithms (base *e*) are most appropriate; this is why they dominate finance and economics.\n\n:::\n\nThe most common logarithm you'll encounter in statistics is the **natural logarithm** (written as \"ln\" or \"log\"), which uses a special number called *e* (approximately 2.718) as its base. Don't worry too much about *e* for now—just know that natural logarithms are the standard in statistical analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# In R, the natural logarithm is simply log():\nlog(100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.60517\n```\n\n\n:::\n\n```{.r .cell-code}\n# The number e in R:\nexp(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.718282\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Business Example: Why Natural Logarithms in Finance\n\nBanks use continuous compounding, which naturally involves *e*. If you invest 1,000 EUR at 5% annual interest compounded continuously:\n\n- After 1 year: $1000 \\times e^{\\left(0.05×1\\right)} = 1,051.27$ EUR\n- After 10 years: $1000 \\times e^{\\left(0.05×10\\right)} = 1,648.72$ EUR\n\nTaking the natural logarithm lets you easily work backwards: if your investment grew to €2,000, you can find how long it took by calculating ln(2000/1000) ÷ 0.05 = 13.86 years.\n:::\n\n## The natural logarithm and exponential functions\n\nThe natural logarithm and the exponential function $e^x$ are mathematical inverses—they undo each other. If you apply one and then the other, you get back to where you started:\n\n- $\\ln\\left(e^x\\right)=x$\n- $e^{\\ln\\left(x\\right)}=x$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Demonstrating that log and exp undo each other:\nx <- 5\nlog(exp(x))  # Should give us 5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(log(x))  # Should also give us 5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\nThis relationship is particularly useful because many real-world processes follow exponential patterns. When something grows exponentially, it increases by a constant percentage over time (like compound interest or viral marketing reach). The exponential function captures this: if you invest 1,000 EUR at 5% annual interest, after *t* years you have $1000 \\times e^{\\left(0.05t\\right)}$ EUR\n\nBy taking the natural logarithm of exponentially growing data, we transform that curved, accelerating relationship into a straight line, as shown in @fig-exponential-transform.\nThis is why this kind of transformation is particularly helpful in the context of linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate exponential data\ntime <- 0:20\nvalue <- 10 * exp(0.15 * time)\n\n# Create data frame\ndf <- data.frame(time = time, value = value, log_value = log(value))\n\n# Plot 1: Original exponential relationship\np1 <- ggplot(df, aes(x = time, y = value)) +\n  geom_point(size = 2, color = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  labs(title = \"Original exponential growth\",\n       x = \"Time\",\n       y = \"Value\") +\n  theme_minimal(base_size = 12)\n\n# Plot 2: Log-transformed relationship (now linear)\np2 <- ggplot(df, aes(x = time, y = log_value)) +\n  geom_point(size = 2, color = \"darkred\") +\n  geom_line(color = \"darkred\", linewidth = 1) +\n  labs(title = \"After log transformation (linear!)\",\n       x = \"Time\",\n       y = \"ln(Value)\") +\n  theme_minimal(base_size = 12)\n\n# Combine plots\nggarrange(p1, p2, ncol = 2, labels = c(\"A)\", \"B)\"))\n```\n\n::: {.cell-output-display}\n![Transforming exponential growth into a linear relationship using the natural logarithm](index_files/figure-pdf/fig-exponential-transform-1.pdf){#fig-exponential-transform fig-pos='H'}\n:::\n:::\n\n\n## When and why do we use logarithms?\n\nLogarithms are useful in statistics and research for a number ofreasons:\n\n**Making skewed data more symmetric.** Many real-world variables—like income, property prices, or company revenues—have a few very large values and many small values. Taking the logarithm compresses those large values and spreads out the small ones, making the data easier to analyze with standard statistical methods, as illustrated in @fig-skewed-data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate skewed income data (lognormal distribution)\nset.seed(123)\nincome <- rlnorm(1000, meanlog = 10, sdlog = 0.8)\n\ndf_income <- data.frame(\n  income = income,\n  log_income = log(income)\n)\n\n# Plot original skewed distribution\np1 <- ggplot(df_income, aes(x = income)) +\n  geom_histogram(bins = 50, fill = \"steelblue\", color = \"white\") +\n  labs(title = \"Original income distribution (highly skewed)\",\n       x = \"Income (€)\",\n       y = \"Frequency\") +\n  theme_minimal(base_size = 12)\n\n# Plot log-transformed distribution\np2 <- ggplot(df_income, aes(x = log_income)) +\n  geom_histogram(bins = 50, fill = \"darkred\", color = \"white\") +\n  labs(title = \"Log-transformed income (more symmetric)\",\n       x = \"ln(Income)\",\n       y = \"Frequency\") +\n  theme_minimal(base_size = 12)\n\nggarrange(p1, p2, ncol = 2, labels = c(\"A)\", \"B)\"))\n```\n\n::: {.cell-output-display}\n![How logarithmic transformation makes skewed data more symmetric](index_files/figure-pdf/fig-skewed-data-1.pdf){#fig-skewed-data fig-pos='H'}\n:::\n:::\n\n\n**Interpreting percentage changes.** When we use logarithms in regression models, our results tell us about proportional or percentage changes rather than absolute changes. For instance, if you're studying how education affects income, using log(income) helps you say \"an extra year of education is associated with a 10% increase in income\" rather than \"an extra year increases income by EUR 5,000\" — which is more meaningful since a 5,000 EUR  increase means very different things to someone earning 20,000 EUR versus 200,000 EUR.\n\n::: {.callout-note collapse=\"true\"}\n## The Mathematics Behind Percentage Interpretation\n\nWhen you use log(Y) as your dependent variable in regression, the coefficient tells you about **proportional changes** rather than absolute changes. Here's why:\n\nIf your regression model is: $\\ln\\left(Y\\right) = \\beta_0 + \\beta_1 X$\n\nThen taking the exponential of both sides: \n\n$$Y = e^{\\left(\\beta_0 + \\beta_1X\\right)} = e^{\\beta_0} \\times e^{(\\beta_1X)}$$\n\nWhen X increases by 1 unit, Y gets multiplied by $e^{\\beta_1}$. For small values of $\\beta_1$ (say, less than 0.15), we can use the approximation:\n\n**Percentage change in $Y\\approx \\beta_1 \\times 100%$**\n\nFor example, if $\\beta_1=0.1$, then a one-unit increase in $X$ is associated with approximately a 10% increase in $Y$.\n\n**Why this matters:** In the education-income example, if ln(Income) = $10.5 + 0.10 \\times $Education:\n- Someone with 12 years of education: predicted income = $e^(10.5 + 0.10\\times 12)$ = 73,700 EUR\n- Someone with 13 years of education: predicted income = $e^(10.5 + 0.10\\times13)$ = 81,450 EUR\n- The increase is EUR 7,750, which is 10.5% of EUR 73,700\n\nNotice that the absolute increase (EUR 7,750) changes depending on the starting income, but the percentage increase ($\\approx10%$) stays constant. This is much more realistic for most economic relationships.\n:::\n\n**Analyzing multiplicative relationships.** Some phenomena grow or shrink by multiplication rather than addition—like compound interest, population growth, or market dynamics. Logarithms transform these multiplicative relationships into additive ones, which are much simpler to work with statistically.\n\n::: {.callout-note collapse=\"true\"}\n## Example: Multiplicative vs. Additive Relationships\n\n**Multiplicative relationship (harder to model):**\nSuppose a product's market share grows by 20% each quarter. Starting at 5%:\n\n- Quarter 0: $5%$\n- Quarter 1: $5% \\times 1.20 = 6%$\n- Quarter 2: $6% \\times 1.20 = 7.2%$\n- Quarter 3: $7.2% \\times 1.20 = 8.64%$\n\nThe relationship is: Market Share(t) = $5% \\times \\left(1.20\\right)^t$\n\nThis is **multiplicative** - we multiply by 1.20 each period. Linear regression struggles with this curved, accelerating pattern.\n\n**After log transformation (additive and linear):**\nTaking the natural logarithm: \n\n$$\\ln(Market Share) = \\ln\\left(5\\%\\right) + t \\times \\ln\\left(1.20\\right)$$\n\n\n\nNow the relationship is **additive** - we add $\\ln\\left(1.20\\right) \\approx 0.182$ each period:\n\n- Quarter 0: $\\ln(5%) = -3.00$\n- Quarter 1: $-3.00 + 0.182 = -2.82$\n- Quarter 2: $-2.82 + 0.182 = -2.64$\n- Quarter 3: $-2.64 + 0.182 = -2.45$\n\nThis is now a simple straight line that standard linear regression can easily handle! The coefficient (0.182) directly tells us the quarterly growth rate.\n\n**Key insight:** Multiplication in the original data becomes addition after log transformation, making complex exponential patterns manageable with basic statistical tools.\n:::\n\n**Handling exponential relationships.** Consider an e-commerce company analyzing how their marketing budget affects monthly revenue. As they scale up spending, each additional euro generates proportionally more revenue due to network effects and brand recognition—a classic exponential pattern.\n\nIf revenue follows the relationship: \n\n$$Revenue = 50,000 \\times e^{\\left(0.00008 \\times Marketing\\right)}$$\n\ntrying to fit a linear regression directly would fail badly. The relationship curves upward, violating the linearity assumption.\n\nBut if we take the natural logarithm of both sides: $\\ln\\left(Revenue\\right) = \\ln\\left(50,000\\right) + 0.00008 \\times Marketing$, we now have a linear relationship that's perfect for regression analysis. The regression coefficient ($\\beta_1$) tells us that each additional euro spent on marketing is associated with approximately a % increase in revenue.\n\nLet's see this in action with a concrete example in @fig-viral-growth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate viral growth data following exponential relationship\nset.seed(789)\nweeks <- 0:20\n# True relationship: Users = 100 * exp(0.15 * Week) \n# 15% weekly growth rate - realistic for early-stage viral apps\ntrue_intercept <- 100\ntrue_growth_rate <- 0.15\nusers <- true_intercept * exp(true_growth_rate * weeks) * exp(rnorm(length(weeks), 0, 0.08))\n\ndf_viral <- data.frame(\n  weeks = weeks,\n  users = users,\n  log_users = log(users)\n)\n\n# Fit linear model on ORIGINAL scale (this will fit poorly)\nmodel_linear <- lm(users ~ weeks, data = df_viral)\n\n# Fit linear model on log-transformed data (this will fit well)\nmodel_log <- lm(log_users ~ weeks, data = df_viral)\n\n# Extract coefficients\nlog_intercept <- coef(model_log)[1]\nlog_growth_coef <- coef(model_log)[2]\ninitial_users <- round(exp(log_intercept), 0)\nweekly_growth_pct <- round(log_growth_coef * 100, 1)\n\n# Calculate final users\nfinal_users <- round(df_viral$users[df_viral$weeks == 20], 0)\n\n# Plot 1: Original scale showing LINEAR model misfit\np1 <- ggplot(df_viral, aes(x = weeks, y = users)) +\n  geom_point(size = 2, color = \"steelblue\") +\n  geom_line(aes(y = predict(model_linear)), \n            color = \"darkred\", linewidth = 1, linetype = \"dashed\") +\n  labs(title = \"Original scale: Linear model misfits badly\",\n       x = \"Weeks since launch\",\n       y = \"Daily active users\",\n       subtitle = \"Red dashed line = linear regression (poor fit)\") +\n  scale_y_continuous(labels = scales::comma) +\n  theme_minimal(base_size = 12)\n\n# Plot 2: Log scale showing perfect linear fit\np2 <- ggplot(df_viral, aes(x = weeks, y = log_users)) +\n  geom_point(size = 2, color = \"steelblue\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"darkred\", fill = \"pink\") +\n  labs(title = \"Log scale: Perfect linear relationship\",\n       x = \"Weeks since launch\",\n       y = \"ln(Users)\",\n       subtitle = \"Red line = linear regression (excellent fit)\") +\n  theme_minimal(base_size = 12)\n\nggarrange(p1, p2, ncol = 2, labels = c(\"A)\", \"B)\"))\n```\n\n::: {.cell-output-display}\n![Linear regression on log-transformed data captures the exponential relationship between time and viral app growth. Left panel shows how a linear model (red dashed line) badly misfits the exponential pattern, while the right panel shows the same data becomes perfectly linear after log transformation.](index_files/figure-pdf/fig-viral-growth-1.pdf){#fig-viral-growth fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n::: {#tbl-logmodel-results .cell tbl-cap='Regression results.'}\n::: {.cell-output-display}\n\n\n|term      | estimate| std_error| statistic| p_value| lower_ci| upper_ci|\n|:---------|--------:|---------:|---------:|-------:|--------:|--------:|\n|intercept |    4.573|     0.025|   186.093|       0|    4.521|    4.624|\n|weeks     |    0.151|     0.002|    71.662|       0|    0.146|    0.155|\n\n\n:::\n:::\n\n\nIn this example, the coefficient for weeks (0.151, see @tbl-logmodel-results) tells us users are growing at approximately 15.1% per week—going from around 97 users at launch to over 1,899 users after 20 weeks. This exponential pattern is typical in the early viral growth phase of successful apps like Instagram, TikTok, or WhatsApp before they hit market saturation.\n\n\n## Summary\n\nYou don't need to calculate logarithms by hand—statistical software handles this automatically. What matters is understanding when and why we use them in our analyses:\n\n- Use logarithms when your data is highly skewed\n- Use logarithms when you're interested in percentage changes rather than absolute changes\n- Use logarithms when relationships are exponential or multiplicative rather than linear\n- Remember that `log()` in R gives you the natural logarithm\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}